// Copyright (c) 2026, Tushar Pokle.  All rights reserved.

/**
 * Generate the similarity noise-floor table baked into
 * web/engine/src/analysis/similarity.ts.
 *
 *     bun web/scripts/generate-similarity-noise-floor.ts
 *
 * The floor answers: what similarity do two pilots who flew NOTHING alike
 * reach, purely because they were compared over only a handful of behaviours?
 * A pair sharing three behaviours clears 0.67 one time in twenty; a pair
 * sharing twenty-two barely reaches 0.21. Without that context a sparse
 * pilot's neighbour list looks exactly like a well-supported one.
 *
 * Why a table rather than a formula. Spearman's floor has a closed form (see
 * spearmanNoiseFloor in analysis/stats.ts, via the t distribution).
 * Tanimoto's does not: T = c / (r + 1/r − c) depends on BOTH the cosine c and
 * the magnitude ratio r = ‖a‖/‖b‖, and both are random, so there is no tidy
 * quantile to invert. A fitted 1.25 / n^0.58 tracks the simulation to ~2%,
 * but a magic exponent is a worse thing to explain than a table of measured
 * numbers, and the domain is tiny — the metric registry holds 32 behaviours.
 *
 * Determinism matters here twice over: the engine's results feed a
 * stale-first cache, and a table that changed on every run would make the
 * scoring generation churn. So this uses a SEEDED generator (mulberry32) and
 * re-running it reproduces the committed numbers exactly.
 */

/** The alpha the floor is quoted at, matching stats.ts's spearmanNoiseFloor. */
const ALPHA = 0.05;
/** Trials per n. 400k keeps the third decimal stable between seeds. */
const TRIALS = 400_000;
/** Two is the fewest behaviours the similarity is defined over; 40 gives the
 * 32-metric registry room to grow. */
const MIN_N = 2;
const MAX_N = 40;
const SEED = 0x9e3779b9;

/** mulberry32 — small, seeded, and good enough for a quantile estimate. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Box–Muller, returning one standard normal per call from a cached pair. */
function normals(rand: () => number): () => number {
  let spare: number | null = null;
  return () => {
    if (spare !== null) {
      const s = spare;
      spare = null;
      return s;
    }
    let u = 0;
    let v = 0;
    while (u === 0) u = rand();
    while (v === 0) v = rand();
    const r = Math.sqrt(-2 * Math.log(u));
    const theta = 2 * Math.PI * v;
    spare = r * Math.sin(theta);
    return r * Math.cos(theta);
  };
}

const rand = mulberry32(SEED);
const randn = normals(rand);

/**
 * One trial: two INDEPENDENT pilots, each a vector of n standard normals —
 * which is what a z-scored behaviour looks like for a pilot whose flying has
 * no relationship to the other's. Returns their Tanimoto.
 */
function trial(n: number): number {
  let dot = 0;
  let sumA = 0;
  let sumB = 0;
  for (let i = 0; i < n; i++) {
    const a = randn();
    const b = randn();
    dot += a * b;
    sumA += a * a;
    sumB += b * b;
  }
  return dot / (sumA + sumB - dot);
}

const rows: string[] = [];
for (let n = MIN_N; n <= MAX_N; n++) {
  const xs = new Float64Array(TRIALS);
  for (let t = 0; t < TRIALS; t++) xs[t] = trial(n);
  xs.sort();
  // One-sided: the sheet ranks by similarity descending, so the question a
  // reader has is always "could this HIGH score have come up by chance?".
  const q = xs[Math.floor((1 - ALPHA) * (TRIALS - 1))];
  rows.push(`  /* ${String(n).padStart(2)} */ ${q.toFixed(3)},`);
}

process.stdout.write(
  `// Generated by web/scripts/generate-similarity-noise-floor.ts — do not edit by hand.\n` +
    `// alpha=${ALPHA}, trials=${TRIALS}, seed=0x${SEED.toString(16)}, n=${MIN_N}..${MAX_N}\n` +
    rows.join('\n') +
    '\n',
);
