#!/usr/bin/env bun
/**
 * Bundles the engine check's sample into a generated module the app can
 * import: one task and its top three tracks from a bundled competition (Corryong Cup
 * 2026, Open, task 1). Metro cannot import .igc or .xctsk files as text, and
 * the samples are too big to copy into the tree, so they are read from
 * web/samples at build time — the same files the engine's own tests use.
 *
 * Writes src/engine-check/sample.generated.ts (gitignored). Every entry point
 * (start, ios, android, test, typecheck) runs this first.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const TASK_DIR = join(import.meta.dir, '../../web/samples/comps/corryong-cup-2026-open-t1');
const TRACKS = [
  'durand_45515_050126.igc',
  'holtkamp_33915_050126.igc',
  'burkitt_18393_050126.igc',
];

const manifest = JSON.parse(
  readFileSync(join(TASK_DIR, '../corryong-cup-2026/comp.json'), 'utf-8'),
) as { gap_params: Record<string, unknown> };

const sample = {
  taskName: 'Corryong Cup 2026 Open, task 1',
  // The comp's own settings (leading and arrival off), as AirScore scored it.
  gapParams: manifest.gap_params,
  xctsk: readFileSync(join(TASK_DIR, 'task.xctsk'), 'utf-8'),
  tracks: TRACKS.map((file) => ({ file, igc: readFileSync(join(TASK_DIR, file), 'utf-8') })),
};

const out = join(import.meta.dir, '../src/engine-check/sample.generated.ts');
writeFileSync(
  out,
  `// Generated by scripts/bundle-engine-sample.ts. Do not edit.\n` +
    `export const SAMPLE = ${JSON.stringify(sample)} as const;\n`,
);
