// Copyright (c) 2026, Tushar Pokle.  All rights reserved.

// Public API
export { sanitizeText } from './sanitize';
export {
  fixAltitude,
  parseIGC,
  type IGCEvent,
  type IGCFile,
  type IGCFix,
  type IGCHeader,
  type IGCTask,
  type IGCTaskPoint,
  type TimeOrderReport,
} from './igc-parser';
export {
  cleanAltitudes,
  type AltitudeCleaningReport,
  type AltitudeRepairRange,
} from './altitude-cleaning';
export { summariseFlight, type FlightSummary } from './flight-summary';
export {
  assessTrackQuality,
  EMPTY_TRACK_QUALITY_REPORT,
  type TrackQualityCheckId,
  type TrackQualityContext,
  type TrackQualityEvidence,
  type TrackQualityFinding,
  type TrackQualityReport,
  type TrackQualitySeverity,
} from './track-quality';
export {
  detectFlight,
  detectFlightEvents,
  filterEventsByBounds,
  getEventStyle,
  type CircleEventDetails,
  type FlightDetectionResult,
  type EventDetails,
  type FixIndexDetails,
  type FlightEvent,
  type FlightEventType,
  type GlideEventDetails,
  type GlideSegment,
  type ThermalEventDetails,
  type ThermalSegment,
  type TrackSegment,
  type TurnpointCrossingDetails,
  type TurnpointReachingDetails,
} from './event-detector';
export {
  calculateNominalTaskDistance,
  getEffectiveESSIndex,
  getEffectiveSSSIndex,
  getESSIndex,
  getGoalIndex,
  getSSSIndex,
  igcTaskToXCTask,
  isValidTask,
  parseXCTask,
  parseXCTaskAsync,
  toXctskJSON,
  type GoalConfig,
  type IGCTaskConversionOptions,
  type SSSConfig,
  type Turnpoint,
  type TurnpointType,
  type Waypoint,
  type XCTask,
} from './xctsk-parser';
export {
  calculateOptimizedTaskDistance,
  calculateOptimizedTaskLine,
  computeTurnpointDirections,
  getOptimizedSegmentDistances,
  type TurnpointDirection,
} from './task-optimizer';
export {
  findWaypoint,
  findWaypointByCoordinates,
  findWaypointByName,
  parseWaypointsCSV,
  type WaypointRecord,
} from './waypoints';
export {
  cleanWaypointCode,
  cleanWaypointCodes,
  describeCodeChanges,
  parseCoordinateValue,
  parseWaypointFile,
  parseWaypointsCUP,
  parseWaypointsFsGeo,
  parseWaypointsGPX,
  parseWaypointsKML,
  parseWaypointsPCX5,
  parseWaypointsUTM,
  parseWaypointsWPT,
  type ParsedWaypointFile,
  type WaypointCodeChange,
  type WaypointFileFormat,
  type WaypointFileRecord,
} from './waypoint-files';
export {
  encodeTurnpointZ,
  encodeXctskQR,
  getWaypointExportFormat,
  swapCodeName,
  toCompeGPS,
  toCSV,
  toFsGeo,
  toFsUtm,
  toGPX,
  toKML,
  toOziExplorer,
  toSeeYouCup,
  WAYPOINT_EXPORT_FORMATS,
  xctaskTurnpointsToRecords,
  XCTSK_QR_MAX_BYTES,
  type WaypointExportFormat,
} from './waypoint-export';
export {
  forgeIgc,
  buildFlight,
  courseFor,
  forgeRange,
  openDistanceCourse,
  OPEN_DISTANCE_MAX_METERS,
  OPEN_DISTANCE_DEFAULT_METERS,
  turnpointsFromTask,
  zoneOffsetHours,
  startSecondsFor,
  type ForgeTurnpoint,
  type ForgeOptions,
  type ForgedTrack,
  type ForgeResult,
  type ForgeSabotage,
} from './forge-igc';
export {
  ellipsoidDistance,
  bearingFromComponents,
  calculateBearing,
  calculateBearingRadians,
  calculateTrackDistance,
  destinationPoint,
  getBoundingBox,
  getCirclePoints,
  isInsideCylinder,
  localEastNorth,
  metresPerDegree,
} from './geo';
export {
  computeGoalLine,
  distanceToGoalLine,
  goalLineCrossing,
  goalLineCrossingFraction,
  goalLinePointAt,
  goalLineToleranceM,
  goalSemicirclePoints,
  goalZoneRadius,
  isForwardGoalCrossing,
  isInGoalSemicircle,
  type GoalLine,
} from './goal-line';
export { utmToLatLon } from './utm';
export { nextDayISO, zonedDayStartMs, zoneOffsetMs } from './zone-offset';
export {
  DEFAULT_UNITS,
  formatAltitude,
  formatAltitudeChange,
  formatClimbRate,
  formatCylinderRadius,
  formatDistance,
  formatRadius,
  formatSpeed,
  formatUnit,
  getCurrentUnit,
  getSegmentLengthMeters,
  getUnitLabel,
  TO_SI,
  type AltitudeUnit,
  type ClimbRateUnit,
  type DistanceUnit,
  type FormattedValue,
  type SpeedUnit,
  type UnitPreferences,
} from './units';
export {
  calculateGlideMarkers,
  calculateGlidePositions,
  calculatePointMetrics,
  calculateTotalGlideDistance,
  requiredGlideToTarget,
  type ChevronPosition,
  type GlideContext,
  type GlideContextResolver,
  type GlideMarker,
  type PointMetrics,
} from './glide-speed';
export {
  detectCylinderCrossings,
  resolveTurnpointSequence,
  reviveTurnpointSequenceResult,
  type BestProgress,
  type BestProgressJSON,
  type CylinderCrossing,
  type CylinderCrossingJSON,
  type EarlyStart,
  type EarlyStartJSON,
  type LaunchWindowInfo,
  type LaunchWindowInfoJSON,
  type LegDistance,
  type StartGateTaken,
  type StartGateTakenJSON,
  type StopResolutionOptions,
  type TaskDeadlineInfo,
  type TaskDeadlineInfoJSON,
  type TaskStopInfo,
  type TaskStopInfoJSON,
  type TurnpointReaching,
  type TurnpointReachingJSON,
  type TurnpointSequenceResult,
  type TurnpointSequenceResultJSON,
} from './turnpoint-sequence';
export {
  gateIndexForCrossing,
  parseTimeOfDayUTC,
  resolveLaunchWindowOpen,
  resolveStartGates,
  resolveTaskDeadline,
  resolveTimeOfDayNear,
} from './time-gates';
export {
  computeBearingRates,
  detectCircles,
  fitCircleLeastSquares,
  normalizeBearingDelta,
  type CircleDetectionResult,
  type CircleSegment,
  type CirclingSegment,
  type FittedCircle,
  type TurnDirection,
  type WindEstimate,
} from './circle-detector';
export {
  sinksFromGlides,
  type ClimbData,
  type FlightSegments,
  type GlideData,
  type SinkData,
} from './segment-extractors';
export { maxBy, minBy } from './array-utils';
export {
  colorForName,
  FLOATS_PER_VERTEX,
  packTracks,
  type PackedTracks,
  type PackInput,
  type PilotTrackInput,
  type TrackFix,
  type TrackManifest,
  type TrackPilotMeta,
  type TrackTaskPoint,
} from './track-packer';
export {
  clusterFrame,
  DEFAULT_GAGGLE_PARAMS,
  detectGaggles,
  gagglesAt,
  type ActiveGaggle,
  type DetectOptions,
  type Frame,
  type GaggleEpisode,
  type GaggleParams,
  type GaggleResult,
  type PilotState,
  type StartCylinder,
  type TurnpointXZ,
} from './cluster-detector';
export { packTracksFromIgc, type PilotIgc, type PackFromIgcInput } from './track-pack-pipeline';
export {
  DEFAULT_THRESHOLDS,
  resolveThresholds,
  type CircleThresholds,
  type DetectionThresholds,
  type GlideThresholds,
  type PartialThresholds,
  type TakeoffLandingThresholds,
  type ThermalThresholds,
  type VarioThresholds,
} from './thresholds';
export {
  formatThresholdForDisplay,
  parseThresholdInput,
  type ParsedThresholdInput,
  type ThresholdDimension,
} from './threshold-parser';
export {
  applyMinimumDistance,
  calculateArrivalPoints,
  calculateDistancePoints,
  calculateDistanceValidity,
  calculateLaunchValidity,
  calculateLeadingCoefficient,
  calculateLeadingPoints,
  calculateSpeedFraction,
  calculateStoppedTaskValidity,
  calculateTaskValidity,
  calculateTimePoints,
  calculateTimeValidity,
  calculateWeights,
  combineLeadingCoefficient,
  computeLeadingAggregate,
  DEFAULT_GAP_PARAMETERS,
  defaultLeadingTimeRatio,
  defaultsFor,
  leadingFormulaFor,
  MAX_LEADING_TIME_RATIO,
  NOMINAL_GOAL,
  NOMINAL_LAUNCH,
  resolveCompGapParams,
  resolveGoalAltitude,
  resolveLeadingMaxTime,
  resolveLeadingTimeRatio,
  resolveScoredWindowEnds,
  resolveTaskStop,
  SCORE_BACK_SECONDS_HG,
  SCORE_BACK_SECONDS_PG,
  scoreBackSecondsFor,
  scoreFlights,
  scoreTask,
  STOPPED_GLIDE_RATIO_HG,
  STOPPED_GLIDE_RATIO_PG,
  stoppedGlideRatio,
  stoppedMinimumRunSeconds,
  taskForDistanceOrigin,
  toFlightScoringData,
  type AvailablePoints,
  type DistanceOrigin,
  type FlightLeadingInput,
  type FlightScoringData,
  type GAPParameters,
  type GapTaskScoreCore,
  type GapTaskScoreResult,
  type LeadingAggregate,
  type LeadingFieldTimes,
  type LeadingFormula,
  type LeadingMaxTime,
  type LeadingMaxTimeSource,
  type LeadingTimes,
  type OpenDistanceTaskScoreCore,
  type OpenDistanceTaskScoreResult,
  type PilotFlight,
  type PilotScore,
  type PilotScoreCore,
  type ScoreTaskOptions,
  type ScoringPreset,
  type StoppedTaskScore,
  type StoppedValidityInputs,
  type TaskScoreCore,
  type TaskScoreResult,
  type TaskStats,
  type TaskStopContext,
  type TaskValidity,
  type TimePointsInput,
  type WeightFractions,
} from './gap-scoring';
export {
  isOpenDistanceTask,
  openDistanceForFlight,
  openDistanceGeometryForFlight,
  scoreOpenDistance,
  scoreOpenDistanceFlights,
  type OpenDistanceFlightData,
  type OpenDistanceGeometry,
} from './open-distance-scoring';
export {
  distanceMadeGoodTo,
  manualFlightGeometry,
  manualFlightScoringData,
  manualOpenDistanceGeometry,
  type ManualFlight,
  type ManualFlightGeometry,
  type ManualOpenDistanceGeometry,
} from './manual-flight';
export { SCORING_ENGINE_VERSION, SCORING_SOURCE_FINGERPRINT } from './scoring-version';
export {
  aggregateComp,
  airborneSeconds,
  ALL_METRICS,
  buildFieldContext,
  buildTimeGrid,
  circularMeanWind,
  clusterPilotStyles,
  clusterSharedThermals,
  findSimilarPilots,
  MIN_COSINE_METRICS,
  similarityNoiseFloor,
  combineWindEstimates,
  correlationVerdict,
  DEFAULT_PHASE_OPTIONS,
  DEFAULT_SHARED_THERMAL_OPTIONS,
  DEFAULT_THERMAL_SHAPE_OPTIONS,
  estimateWorkingBand,
  evaluateField,
  extractThermalShapes,
  FAMILY_LABELS,
  FAMILY_ORDER,
  TASK_ANALYSIS_VERSION,
  formatMetricValue,
  mean,
  median,
  MIN_CLUSTER_PILOTS,
  MIN_CORRELATION_N,
  MIN_COVERAGE,
  partitionPhases,
  percentile,
  rankWithTies,
  renderCompAnalysis,
  renderTaskAnalysis,
  roundPercentagesToHundred,
  sampleAt,
  signConsistency,
  spearman,
  spearmanNoiseFloor,
  stepFor,
  STYLE_NICKNAMES,
  summariseThermalShape,
  type BuildFieldContextOptions,
  type CategoricalReportSeries,
  type ClimbHourlySeries,
  type ClimbQuantiles,
  type CompAnalysisReport,
  type CompMetricAggregate,
  type CompTaskResult,
  type CorrelationVerdict,
  type DayTimingSeries,
  type FieldAirtimeSplit,
  type FindSimilarPilotsOptions,
  type TaskAnalysisBasis,
  type TaskAnalysisReport,
  type FieldContext,
  type FieldThermalsSummary,
  type FlightPhase,
  type LegInfo,
  type MeanWind,
  type MetricComputer,
  type MetricCorrelation,
  type MetricDirection,
  type MetricFamily,
  type MetricOutput,
  type MetricReport,
  type PhaseInterval,
  type PhasePartitionOptions,
  type PilotAnalysisContext,
  type PilotMetricValue,
  type ReportCell,
  type ReportSeries,
  type ReportTable,
  type ResampledSample,
  type ResampledTrack,
  type SharedThermal,
  type SharedThermalOptions,
  type SignatureHint,
  type SimilarityContribution,
  type SimilarityRanking,
  type SimilarPilot,
  type SkippedPilot,
  type PilotSimilarityReport,
  type SignConsistency,
  type SignSummary,
  type StyleCluster,
  type StyleClusterMember,
  type StyleClusterReport,
  type StyleSignature,
  type ThermalLean,
  type ThermalPilotClimb,
  type ThermalSample,
  type ThermalSectorStat,
  type ThermalShape,
  type ThermalShapeBand,
  type ThermalShapeOptions,
  type ThermalShapePilot,
  type ThermalShapeSummary,
  type ThermalSubCore,
  type ThermalUse,
  type ThermalWindEstimate,
  type TimeGrid,
  type UnclusteredPilot,
  type WindHourlySeries,
  type WindLegsSeries,
  type WindSample,
  type WorkingBand,
  type WorkingBandHour,
} from './analysis';
export {
  explainExcludedTrack,
  explainGapScore,
  explainManualFlightScore,
  explainOpenDistanceScore,
  turnpointLabel,
  type ClassContextInput,
  type ExplainGapScoreInput,
  type ExplainManualFlightInput,
  type ExplainOpenDistanceInput,
  type ExplanationAnchor,
  type ExplanationAnchorKind,
  type OpenDistanceAnchorInfo,
  type ScoreChart,
  type ScoreChartPilot,
  type ScoreChartPoint,
  type ScoreChartXUnit,
  type ScoreCurveChart,
  type ScoreDistributionChart,
  type ScoreDistributionMarker,
  type ScoreDistributionPoint,
  type ScoreEntryInput,
  type ScoreExplanation,
  type ScoreExplanationItem,
  type ScoreExplanationSection,
  type ScoreExplanationSectionId,
  type ScoreValidityChart,
} from './score-explanation';
export {
  calculatedFtv,
  computeFtvForPilot,
  explainFtv,
  ftvDiscardFactor,
  type FtvExplanation,
  type FtvPilotResult,
  type FtvTaskBreakdown,
  type FtvTaskInput,
  type FtvTaskStatus,
} from './ftv';
export {
  bestDaylightWindow,
  beyondForecastHorizon,
  DEFAULT_FLYING_HEIGHT_AGL_M,
  DEFAULT_WEATHER_PROVIDERS,
  fetchTaskWeather,
  flyingHeightLevel,
  FORECAST_HORIZON_DAYS,
  heightToPressureHpa,
  lclHeightAglM,
  levelNearestHeight,
  NoWeatherAvailable,
  openMeteoEra5Provider,
  openMeteoForecastProvider,
  openMeteoHistoricalForecastProvider,
  openMeteoProviders,
  pressureToHeightM,
  selectProviders,
  sunTimes,
  taskCentroid,
  WEATHER_SCHEMA_VERSION,
  weatherQueryForTask,
  weatherQueryKey,
  windAtHeight,
  type FetchTaskWeatherOptions,
  type SunTimes,
  type TaskWeather,
  type WeatherFetchContext,
  type WeatherFetchFn,
  type WeatherHour,
  type WeatherLevel,
  type WeatherProvider,
  type WeatherQuery,
  type WeatherSource,
  type WeatherSourceKind,
  type WeatherVariable,
} from './weather';
